name: Python
on:
  workflow_call:
    secrets:
      PYPI_PASSWORD:
        required: false
      TEST_PYPI_PASSWORD:
        required: false
    inputs:
      workdir:
        type: string
        default: src
      python-version: 
        type: string
        default: 3.11.3

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Publish Snapshot to TestPyPi
        uses: microsoft/action-python@0.6.4
        continue-on-error: true
        if: ${{ github.event_name == 'pull_request' }}
        with:
          pypi_publish: true
          pypi_password: ${{ secrets.TEST_PYPI_PASSWORD  }}
          pypi_repo: testpypi
          version_suffix: -post${{ github.run_number }}-dev${{ github.run_attempt }}
          workdir: ${{ inputs.workdir }}
          python_version: ${{ inputs.python-version }}

      - name: Publish RC to PyPi
        uses: microsoft/action-python@0.6.4
        if: ${{ github.event_name == 'push' }}
        with:
          pypi_publish: true
          pypi_password: ${{ secrets.PYPI_PASSWORD }}
          version_suffix: -rc${{ github.run_number }}-post${{ github.run_attempt }}
          workdir: ${{ inputs.workdir }}
          python_version: ${{ inputs.python-version }}

      - name: Publish Release to PyPi
        uses: microsoft/action-python@0.6.4
        if: ${{ github.event_name == 'release' }}
        with:
          pypi_publish: true
          pypi_password: ${{ secrets.PYPI_PASSWORD }}
          workdir: ${{ inputs.workdir }}
          python_version: ${{ inputs.python-version }}
